name: Build, test and deploy to s3

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build with Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: false
    - run: npm test --passWithNoTests
    - name: Upload to S3 Bucket
      run: AWS_DEFAULT_REGION=ap-southeast-2 AWS_ACCESS_KEY_ID=${{secrets.AWS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} aws s3 sync ./build/ s3://wormle
          
      