name: Push to main

on:
  push:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present
        env:
          CI: false

      - name: Test
        run: npm test

      - name: Upload to S3 Bucket
        env:
          AWS_DEFAULT_REGION: ap-southeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync ./build/ s3://wormle

  invoke-lambda:
    runs-on: ubuntu-latest
    needs: build-test-deploy

    steps:
      - name: Invoke Lambda
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws lambda invoke --region us-east-1 --function-name uploadLatestDatabaseGame --cli-binary-format raw-in-base64-out response.json
